### ISSUE TITLE
APK File With Different Names

### ISSUE THREAD

**Issue by SharpMobileCode** [azchohfi/vsts-task-publish-playstore#2]
I'm trying to use the VSTS Task to deploy my production *.apk file to Google Play.  Under the "APK File" text box I type in:

>$(System.DefaultWorkingDirectory)\ReleaseName\drop\production\release\*.apk

I can not specify a specific file name because for each build the *.apk file name will be different based on a build number.  For example, the "Build 123 " file name will be "my-awesome-app-build-123.apk" and "Build 124" will be "my-awesome-app-build-124.apk", etc.

The VSTA Task doesn't seem to support variable *.apk names like the path I'm entering above.  I get the following error:

>OSError: [Errno 22] Invalid argument: 'd:\\a\\r1\\a\\ReleaseName\\drop\\production\\release\\*.apk'

Any idea how I can give it a variable apk name?  It's going to be different every build and due to other requirements it must have a unique name for every build.

**Comment by azchohfi** [comment]
Use the Microsoft official task: https://marketplace.visualstudio.com/items?itemName=ms-vsclient.google-play

**Comment by SharpMobileCode** [comment]
Thanks!  I didn't realize there was one by Microsoft as it was not installed on our VSTS online instance by default.  I had to get an admin to install it.  Once I installed and it, it worked on the first shot.  Seems strange how the official Microsoft one is not installed by default.

Thank you!
